# Generated by Django 2.2.5 on 2021-03-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_content', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_author', models.CharField(default='', max_length=100)),
                ('quote_content', models.CharField(max_length=600)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='GifsQuestionMark.Tags')),
            ],
        ),
    ]
