# Generated by Django 2.2.5 on 2021-03-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GifsQuestionMark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='GifsQuestionMark.Tags'),
        ),
    ]
